### ISSUE TITLE
[BUG] extension window very small

### ISSUE THREAD

**Issue by mangkoran** [SevenTV/Extension#1052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Chrome

### Current Behavior

When I click extension icon, the extension window shows with very small width making it impossible to config. Note that I have disabled all of my extensions.

![image](https://github.com/SevenTV/Extension/assets/57625126/1a7c829a-277c-4f72-876f-c1149f02062c)

![image](https://github.com/SevenTV/Extension/assets/57625126/228ccc16-014d-4078-86ce-2d2c62e259a2)

### Expected Behavior

Extension window has normal width which show config.

### Steps To Reproduce

1. Install `Chrome Version 126.0.6478.127 (Official Build) (64-bit)`
2. Install `7TV 3.0.9` or `7TV Nightly 3.0.15.1000 nightly`

**Comment by mangkoran** [comment]
If I override the width manually it will show.

```css
html[data-seventv-app] {
    box-sizing: border-box;
    font-family: Roboto, sans-serif;
    height: 100%;
    width: 400px; /* it was 100% before */
}
```

![image](https://github.com/SevenTV/Extension/assets/57625126/99aaa23a-3907-4c30-9cd4-b37ae6cabd0c)
